# WORKING WITH COLOR CHANNEL

In [48]:
#importing necessary library
import cv2 as cv
import numpy as np

In [49]:
#import photo
photo=cv.imread("photo.jpeg")
cv.imshow("photo",photo)
cv.waitKey(0)
cv.destroyAllWindows()

In [50]:
#Creating blank image
blank=np.zeros((photo.shape[:2]),dtype="uint8")
cv.imshow("Blank",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [51]:
#BGR channel is divided
b,g,r=cv.split(photo)
cv.imshow("Blue",b)
cv.imshow("Green",g)
cv.imshow("Red",r)
cv.waitKey(0)
cv.destroyAllWindows()

In [52]:
#Three channel B,G,R is combined
blue=cv.merge([b,blank,blank])
green=cv.merge([blank,g,blank])
red=cv.merge([blank,blank,r])
cv.imshow("Blue",blue)
cv.imshow("Green",green)
cv.imshow("Red",red)
cv.waitKey(0)
cv.destroyAllWindows()

# Types of BLURRING

In [6]:

#kernel size of block in a image
#For example if we choose kernal size of 3, It will divide 1 block divided with 3X3 pixel over the image.
#average blur is a technique for blurring in which center pixel is the average of all the surrounding pixel, 
#i.e, pixel 5 is the avarage of all the pixel 
#[ [1][2][3]
#  [4][5][6]
#  [7][8][9] ] pixel 5 is the average of all pixel 1,2,3,4,6,7,8,9
cv.imshow("original image",photo)
avg=cv.blur(photo,(3,3))
cv.imshow("average",avg)
cv.waitKey(0)
cv.destroyAllWindows()

In [70]:
#Gaussian Blur is a technique for blurring in which center pixel is the sum of the product of all the surrounding pixel and 
#weight,i.e, pixel 5 is the avarage of all the pixel
#[ [1][2][3]
#  [4][5][6]
#  [7][8][9] ] pixel 5 is the average of all pixel 1,2,3,4,6,7,8,9
gauss=cv.GaussianBlur(photo,(3,3),1)
cv.imshow("Guass",gauss)
cv.waitKey(0)
cv.destroyAllWindows()

In [8]:
#Median Blur is a technique for blurring in which center pixel is the median of all the surrounding pixel
#[ [1][2][3]
#  [4][5][6]
#  [7][8][9] ] pixel 5 is the Median of all pixel 1,2,3,4,6,7,8,9
Median=cv.medianBlur(photo,5)
cv.imshow("Median Blur",Median)
cv.waitKey(0)
cv.destroyAllWindows()

In [76]:
#Bilateral Blur
bilateral=cv.bilateralFilter(photo,10,20,20)
cv.imshow("Bilateral",bilateral)
cv.waitKey(0)
cv.destroyAllWindows()

# BITWISE OPERATION

In [81]:
import numpy as np
import cv2 as cv
blank=np.zeros(photo.shape[:],dtype="uint8")
cv.imshow("Blank",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [102]:
rectangle=cv.rectangle(blank.copy(),(500,500),(750,750),(0,0,255),-1)
cv.imshow("Rectangle",rectangle)
cv.waitKey(0)
cv.destroyAllWindows()

In [116]:
circle=cv.circle(blank.copy(),(500,500),250,(0,0,255),-1)
cv.imshow("Rectangle",circle)
cv.waitKey(0)
cv.destroyAllWindows()

In [119]:
And=cv.bitwise_and(circle,rectangle)
cv.imshow("And operation",And)
cv.waitKey(0)
cv.destroyAllWindows()

In [14]:
Or=cv.bitwise_or(rectangle,circle)
cv.imshow("Or operation",Or)
cv.waitKey(0)
cv.destroyAllWindows()

In [15]:
xor=cv.bitwise_xor(rectangle,circle)
cv.imshow("XOR",xor)
cv.waitKey(0)
cv.destroyAllWindows()

In [120]:
Not=cv.bitwise_not(circle)
cv.imshow("Not operation",Not)
cv.waitKey(0)
cv.destroyAllWindows()

# MASKING

In [17]:
photo=cv.imread("photo.jpeg")
cv.imshow("photo",photo)
print(photo.shape[:])
cv.waitKey(0)
cv.destroyAllWindows()

(1280, 960, 3)


In [18]:
import cv2 as cv
import numpy as np
blank=np.zeros((photo.shape[:3]),dtype="uint8")

In [19]:
cv.imshow("blank",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [20]:
rectangle=cv.rectangle(blank.copy(),((photo.shape[1]//2)-200,(photo.shape[0]//2)-200),
                       ((photo.shape[1]//2)+200,(photo.shape[0]//2)+200),(255,255,255),-1)
cv.imshow("Rectangle",rectangle)
cv.waitKey(0)
cv.destroyAllWindows()

In [21]:
Bitwise_And=cv.bitwise_and(rectangle,photo)
cv.imshow("Masking",Bitwise_And)
cv.waitKey(0)
cv.destroyAllWindows()

In [22]:
Bitwise_Or=cv.bitwise_or(photo,rectangle)
cv.imshow("Or masking",Bitwise_Or)
cv.waitKey(0)
cv.destroyAllWindows()

# HISTOGRAM

In [23]:
#Library imported
import cv2 as cv
import numpy as np
import matplotlib.pyplot as py
#pop out graph
%matplotlib qt 

In [24]:
#Photo is imported
image=cv.imread("Photo.jpeg")
cv.imshow("Photo",image)
cv.waitKey(0)
cv.destroyAllWindows()

#Blank image is imported
blank=np.zeros(image.shape[:2],dtype="uint8")
cv.imshow("BLANK",blank)
cv.waitKey(0)
cv.destroyAllWindows()


In [25]:
#Color channel is splited
b,g,r=cv.split(image)
blue=cv.merge([b,blank,blank])         #RGB->#BGR
cv.imshow("blue",b)
cv.imshow("blue",blue)
cv.waitKey(0)
cv.destroyAllWindows()

In [26]:
#Rectangle is drawn over a image
#blank.copy is used so that blank image doesnot get updated
rectangle=cv.rectangle(blank.copy(),((photo.shape[1]//2)-200,(photo.shape[0]//2)-200),
                       ((photo.shape[1]//2)+200,(photo.shape[0]//2)+200),(255,255,255),-1)
cv.imshow("Rectangle",rectangle)
cv.waitKey(0)
cv.destroyAllWindows()

In [121]:
#image is converted to greyscale
grey_scale=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
cv.imshow("GreyScale",grey_scale)
#Histogram is created
#Histogram is created for a particular area
grey_hist1=cv.calcHist([b],[1],rectangle,[256],[0,256])
grey_hist2=cv.calcHist([g],[0],rectangle,[256],[0,256])
grey_hist3=cv.calcHist([r],[0],rectangle,[256],[0,256])
plot1=py.figure(1)
py.plot(grey_hist1)
plot1=py.figure(2)
py.plot(grey_hist2)
plot1=py.figure(3)
py.plot(grey_hist3)
cv.waitKey(0)
cv.destroyAllWindows()

error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-u4kjpz2z\opencv\modules\imgproc\src\histogram.cpp:993: error: (-215:Assertion failed) mask.empty() || mask.type() == CV_8UC1 in function 'cv::calcHist'


In [28]:
#Histogram is created for whole image
grey_hist1=cv.calcHist([b],[0],None,[256],[0,256])
plot4=py.figure(4)
py.plot(grey_hist1)

# THRESHOLDING

In [127]:
#simple thresholding
threshold, thres=cv.threshold(grey_scale,80,255,cv.THRESH_BINARY)
cv.imshow("Thresholding",thres)
cv.waitKey(0)
cv.destroyAllWindows()

In [123]:
#inverse threshold
threshold,thres=cv.threshold(grey_scale,80,255,cv.THRESH_BINARY_INV)
cv.imshow("Thresholding",thres)
cv.waitKey(0)
cv.destroyAllWindows()

In [129]:
#ADAPTIVE THRESHOLD
Adaptive_thresh=cv.adaptiveThreshold(grey_scale,200,cv.ADAPTIVE_THRESH_MEAN_C,cv.THRESH_BINARY,11,9)
cv.imshow("Adaptive",Adaptive_thresh)
cv.waitKey(0)
cv.destroyAllWindows()

In [131]:
#different method used to determine
Adaptive_thresh_guass=cv.adaptiveThreshold(grey_scale,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,cv.THRESH_BINARY,11,9)
cv.imshow("Adaptive",Adaptive_thresh)
cv.waitKey(0)
cv.destroyAllWindows()

# EDGE DETECTION

In [33]:
#Laplacian
lap=cv.Laplacian(grey_scale,cv.CV_32F)
lap=np.uint8(np.absolute(lap))
cv.imshow("Laplacian",lap)
cv.waitKey(0)
cv.destroyAllWindows()

In [46]:
#SObel
sobelx=cv.Sobel(grey_scale,cv.CV_64F,1,0)
sobely=cv.Sobel(grey_scale,cv.CV_64F,1,1)
cv.imshow("SobelX",sobelx)
cv.imshow("SobelY",sobely)
cv.waitKey(0)
cv.destroyAllWindows()

In [47]:
#Merged sobelx and sobely
merged_image=cv.bitwise_or(sobelx,sobely)
cv.imshow("Merge image",merged_image)
cv.waitKey(0)
cv.destroyAllWindows()

In [36]:
#Canny edge detection
Canny=cv.Canny(grey_scale,100,200)
cv.imshow("Canny",Canny)
cv.waitKey(0)
cv.destroyAllWindows()

# WRAP PRESPECTIVE

In [132]:
import cv2 as cv
import numpy as np
cards=cv.imread("cards.jpg")
cv.imshow("CARDS",cards)
cv.waitKey(0)
cv.destroyAllWindows()

In [133]:
points=np.float32([[0,0],[cards.shape[1],0],[0,cards.shape[0]],[cards.shape[1],cards.shape[0]]])
points1=np.float32([[89,21],[227,22],[70,171],[215,170]])
points2=np.float32([[251,18],[391,15],[249,169],[398,162]])
matrix1=cv.getPerspectiveTransform(points1,points)
matrix2=cv.getPerspectiveTransform(points2,points)
print(matrix1,matrix2)
imageOutput1=cv.warpPerspective(cards,matrix1,cards.shape[:2])
imageOutput2=cv.warpPerspective(cards,matrix2,cards.shape[:2])
cv.imshow("cards image",cards)
cv.imshow("OUTPUT IMAGE1",imageOutput1)
cv.imshow("OUTPUT IMAGE2",imageOutput2)
circle=cv.circle(cards.copy(),(cards.shape[1]//2,cards.shape[0]//2),1,(0,255,255),2)
cv.imshow("circle",circle)
cv.waitKey(0)
cv.destroyAllWindows()

[[ 4.63560426e+00  5.87176540e-01 -4.24899487e+02]
 [-3.14467625e-02  4.33965322e+00 -8.83339558e+01]
 [-9.64861509e-05  3.17279468e-04  1.00000000e+00]] [[ 4.39181215e+00  5.81696973e-02 -1.10339190e+03]
 [ 9.11317438e-02  4.25281471e+00 -9.94247325e+01]
 [-1.55035781e-04  4.18618978e-04  1.00000000e+00]]


# JOINING IMAGE

In [39]:
imgHor=np.hstack((imageOutput1,imageOutput1,imageOutput1))
imgVer=np.vstack((imageOutput1,imageOutput1,imageOutput1))
cv.imshow("Horizontal View",imgHor)
cv.imshow("Vertical View",imgVer)
cv.waitKey(0)
cv.destroyAllWindows()

In [40]:
import cv2
import cv2 as cv
def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0),cv.INTER_AREA, scale,scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]))
                if len(imgArray[x][y].shape) == 2:
                    imgArray[x][y]= cv2.cvtColor(imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3),np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.vstack(imgArray[x])
        ver = np.hstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: 
                imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver

In [41]:
grey_image=cv.cvtColor(cards,cv.COLOR_BGR2GRAY)
cv.imshow("GRAY IMAGE",grey_image)
color=cv.cvtColor(grey_image,cv.COLOR_GRAY2BGR)
cv.imshow("COloring",color)
imageStack=stackImages(0.5,([cards,cards,grey_image,cards,cards],[cards,cards,grey_image,cards,cards],[cards,cards,grey_image,cards,cards]))
cv.imshow("IMAGE STACK",imageStack)
print(len(cards.shape))
cv.waitKey(0)
cv.destroyAllWindows()

3


# COLOR DETECTION

In [42]:
import cv2 as cv
import cv2
import numpy as np

def empty(a):
    pass

#path = 'Resources/lambo.png'
cv2.namedWindow("TrackBars")
cv2.resizeWindow("TrackBars",720,240)  
cv2.createTrackbar("Hue Min","TrackBars",0,179,empty)
cv2.createTrackbar("Hue Max","TrackBars",179,179,empty)
cv2.createTrackbar("Sat Min","TrackBars",0,255,empty)
cv2.createTrackbar("Sat Max","TrackBars",255,255,empty)
cv2.createTrackbar("Val Min","TrackBars",0,255,empty)
cv2.createTrackbar("Val Max","TrackBars",255,255,empty)

video=cv.VideoCapture(0)
while True:
    success,frame=video.read()
    if(cv.waitKey(1) & 0xFF==ord('q') or success==False):
        break
    cv.imshow("Camera",frame)
video.release()
cv.destroyWindow("Camera")
while True:
    #img = cv2.imread(path)
    img=frame
    imgHSV = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    h_min = cv2.getTrackbarPos("Hue Min", "TrackBars")
    print(h_min)
    h_max = cv2.getTrackbarPos("Hue Max", "TrackBars")
    s_min = cv2.getTrackbarPos("Sat Min", "TrackBars")
    s_max = cv2.getTrackbarPos("Sat Max", "TrackBars")
    v_min = cv2.getTrackbarPos("Val Min", "TrackBars")
    v_max = cv2.getTrackbarPos("Val Max", "TrackBars")
    #print(h_min,h_max,s_min,s_max,v_min,v_max)
    lower = np.array([h_min,s_min,v_min])
    upper = np.array([h_max,s_max,v_max])
    
    #print(upper,lower)
    
    mask = cv2.inRange(imgHSV,lower,upper)
    imgResult = cv2.bitwise_and(img,img,mask=mask)

    # cv2.imshow("Original",img)
    # cv2.imshow("HSV",imgHSV)
    # cv2.imshow("Mask", mask)
    # cv2.imshow("Result", imgResult)

    imgStack = stackImages(0.5,[[img,imgHSV],[mask,imgResult]])
    cv2.imshow("Stacked Images", imgStack)
    if (cv2.waitKey(1) & 0xFF == ord('q')):
        break
cv.destroyAllWindows()


error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-u4kjpz2z\opencv\modules\highgui\src\window_w32.cpp:1246: error: (-27:Null pointer) NULL window: 'Camera' in function 'cvDestroyWindow'
