In [1]:
import cv2 as cv

In [2]:
def rescaling(width,height):
    #works only on live video
    capture.set(3,width)
    capture.set(4,height)

In [3]:
def resolution(frame,ratio=1.25):
    # works on video, photo,live video
    width=int(frame.shape[1] * ratio)
    height=int(frame.shape[0]*ratio)
    dimension=(width,height)
    return cv.resize(frame,dimension,interpolation=cv.INTER_AREA)


def resolution1(frame,ratio=0.5):
    # works on video, photo,live video
    width=int(frame.shape[1] * ratio)
    height=int(frame.shape[0]*ratio)
    dimension=(width,height)
    return cv.resize(frame,dimension,interpolation=cv.INTER_CUBIC)

In [4]:
image=cv.imread('photo.jpeg')
cv.imshow("photo viewer",image)
cv.imshow("Photo decrement",resolution(image))
cv.imshow("Photo linear",resolution1(image))
cv.waitKey(0)
cv.destroyAllWindows()

In [5]:
vid = cv.VideoCapture(0)
while(True):
    ret, frame = vid.read()
    if (cv.waitKey(1) & 0xFF == ord('q')) or ret==False:
        break
    
    ModFrame=resolution(frame)
    cv.imshow('frame', ModFrame)
vid.release()
cv.destroyAllWindows()


In [6]:
#creating blank image
import numpy as np
blank=np.zeros((5000,5000,3),dtype="uint8")
cv.imshow("blank",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [7]:
#drawing in the image
blank[:]=0,0,255
cv.imshow("blank",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [8]:
#coluring specific area
blank=np.zeros((500,500,3),dtype="uint8")
cv.imshow("blank",blank)
blank[200:300,250:350]=0,0,255
cv.imshow("blank",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [9]:
import numpy as np
blank=np.ones((500,500,3),dtype="uint8")

In [10]:
#Creating rectangle
cv.rectangle(blank,(0,0),(550,250),(0,200,150),thickness=1)
cv.imshow("rectangle",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [11]:
#Creating rectangle
#thickness=cv.FILLED fill the shape with color
cv.rectangle(blank,(0,0),(550,250),(0,255,0),thickness=cv.FILLED)
cv.imshow("rectangle",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [12]:
#Creating circle
cv.circle(blank,(250,250),200,(255,0,0),thickness=-1)
cv.imshow('circle',blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [13]:
#Creating line
cv.line(blank,(250*2,250*2),(0,0),(255,0,0),thickness=3)
cv.imshow('line',blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [14]:
#putting text
cv.putText(blank,"Hello my name is manash das",(0,255),cv.FONT_HERSHEY_TRIPLEX,0.5,(0,255,0),1)
cv.imshow('TEXT',blank)
cv.waitKey(0)
cv.destroyAllWindows()

# # Image Transformation

In [15]:
#creating image in greyscale
image=cv.imread('photo.jpeg')
image=resolution(image)
grey=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
cv.imshow("image",image)
cv.imshow("Grey",grey)
cv.waitKey(0)
cv.destroyAllWindows()

In [16]:
#Blur image
image=cv.imread('photo.jpeg')
image=resolution(image)
cv.imshow('original image',image)
blur=cv.GaussianBlur(image,(3,3),cv.BORDER_DEFAULT)
cv.imshow('Blur image',blur)
cv.waitKey(0)
cv.destroyAllWindows()

In [17]:
#Edge detection
canny=cv.Canny(image,150,100)
#canny1=cv.Canny(blur,10,150)
#cv.imshow('Less',canny1)
cv.imshow("Edge detection",canny)
#Dilated
#dilated=cv.dilate(canny1,(1,1),iterations=10)
dilated2=cv.dilate(canny,(1,1),iterations=1)
cv.imshow("Dilated1",dilated2)
#cv.imshow("Dilated2",dilated)
cv.waitKey(0)
cv.destroyAllWindows()

In [20]:
#Dilated
#dilated=cv.dilate(canny1,(1,1),iterations=10)
dilated=cv.dilate(canny,(1,1),iterations=1)
cv.imshow("Dilated1",dilated2)
#cv.imshow("Dilated2",dilated)

cv.waitKey(0)
cv.destroyAllWindows()

In [21]:
#Eroded
Eroded=cv.erode(dilated,(7,7),iterations=3)
cv.imshow("Eroded",Eroded)
cv.waitKey(0)
cv.destroyAllWindows()

In [22]:
#Resize
image=cv.imread('photo.jpeg')
resize=cv.resize(image,(1000,1000),interpolation=cv.INTER_CUBIC)
cv.imshow("image",resize)
cv.waitKey(0)
cv.destroyAllWindows()

In [35]:
#Cropping
image=cv.imread("photo.jpeg")
image=resolution(image)
cropped=image[100:100,300:300]#slicing
cv.imshow("crop",image)
cv.waitKey(0)
cv.destroyAllWindows()

In [39]:
#image shifting
def shifting(img,x,y):
    shift=np.float32([[50,50,x],[50,50,y]])
    print(shift)
    dimension=[img.shape[1],img.shape[0]]
    return cv.warpAffine(img,shift,dimension)

# -x->moves left
# -y->moves up
# x->moves right
# y->moves down
img=resolution(image,0.5)
shifting=shifting(img,100,100)
cv.imshow("shifter image",shifting)
cv.imshow("image",image)

cv.waitKey(0)
cv.destroyAllWindows()

[[ 50.  50. 100.]
 [ 50.  50. 100.]]


In [65]:
#image Rotation
def rotate(image,angle,rotpoint=None):
    (height,width)=image.shape[0:2]
    if(rotpoint==None):
        rotpoint=(width//2,height//2)
    rotMat=cv.getRotationMatrix2D(rotpoint,angle,0.5)
    dimensions=(width,height)
    return cv.warpAffine(image,rotMat,dimensions)

Rotating=rotate(img,45)

cv.imshow("Rotate image",Rotating)

cv.waitKey(0)
cv.destroyAllWindows()
# + angle->anticlockwise
# - angle->clockwise

In [74]:
#flip image
flip=cv.flip(img,-1)
cv.imshow("flip image",flip)
cv.waitKey(0)
cv.destroyAllWindows()

### counter or finding edges 

In [110]:
#Counter
import cv2 as cv
image=cv.imread("photo.jpeg")
canny=cv.Canny(image,200,200)
cv.imshow("canny image",canny)
counter,heirarchies=cv.findContours(canny,cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)
print(heirarchies)
#counter -> stores all coordinates of contours
print(len(counter))
cv.waitKey(0)
cv.destroyAllWindows()

[[[   1   -1   -1   -1]
  [   2    0   -1   -1]
  [   3    1   -1   -1]
  ...
  [2970 2968   -1   -1]
  [2971 2969   -1   -1]
  [  -1 2970   -1   -1]]]
2972


In [90]:
#Blank image
import numpy as np
blank=np.zeros(image.shape,dtype='uint8')
cv.imshow("blank",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [111]:
#Other way of contours
grey=cv.cvtColor(image,cv.COLOR_GRAY2RGB)
#cv.imshow("image",grey)
#img=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
ret,thresh=cv.threshold(grey,120,255,cv.THRESH_BINARY)
cv.imshow("thresh",thresh)
cv.waitKey(0)
cv.destroyAllWindows()

error: OpenCV(4.5.3) c:\users\runneradmin\appdata\local\temp\pip-req-build-u4kjpz2z\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<1,-1,-1>,struct cv::impl::A0x5888afd4::Set<3,4,-1>,struct cv::impl::A0x5888afd4::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 3


In [92]:
#placing contours
cv.drawContours(blank,counter,-1,(0,255,0),1)
cv.imshow("placing contours",blank)
cv.waitKey(0)
cv.destroyAllWindows()

In [118]:
#placing contours
cv.drawContours(blank,ret,-1,(0,255,0),2)
cv.imshow("placing contours",blank)
cv.waitKey(0)
cv.destroyAllWindows()


error: OpenCV(4.5.3) :-1: error: (-3:Internal error) Overload resolution failed, but no errors reported in function 'drawContours'


In [119]:
rgb=cv.cvtColor(image,cv.COLOR_BGR2RGB)
cv.imshow("RGB",rgb)
cv.waitKey(0)

13

In [117]:
#Laplacian
lap=cv.Laplacian(grey,cv.CV_64F)
lap=np.uint8(np.absolute(lap))
cv.imshow("Laplacian",lap)
cv.waitKey(0)
cv.destroyAllWindows()